group:
  # first group
  - files:
      - source: test.txt
        dest: test.txt
    repos: |
      devopslab1729/github-workflows
      devopslab1729/test

  # second group
  # first group
  - files:
      - source: test1.txt
        dest: test1.txt
    repos: |
      devopslab1729/github-workflows
      devopslab1729/test
  # third group
  - files:
      - source: test2.txt
        dest: test3.txt