name: Sync Local Files
on:
  push:
    branches:
      - main
  pull_request:
    types:
        - opened
        - synchronize
        - edited
  workflow_dispatch:
jobs:
  sync-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          PR_LABELS: |
            file-sync
            automerge
          PR_BODY: This is your custom PR Body
          COMMIT_PREFIX: "chore: sync files"
          SKIP_PR: true
          SYNC_CONFIG: .github/sync-local.yml
          